// <auto-generated />
using Discord_Support_Bot.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Discord_Support_Bot.Migrations
{
    [DbContext(typeof(SupportContext))]
    partial class SupportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Discord_Support_Bot.SQLite.Table.TrustedGuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrustedGuild");
                });

            modelBuilder.Entity("Discord_Support_Bot.SQLite.Table.UpdateGuildInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelNitroId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTwitterProfileURL")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("NoticeChangeAvatarChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TwitterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UpdateGuildInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
